name: Triggered Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (e.g., dev, staging, prod)'
        required: true
        default: 'dev'
      debug:
        description: 'Enable debug mode'
        required: false
        default: 'false'
        type: boolean

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Inputs
        run: |
          echo "Running in environment: ${{ github.event.inputs.environment }}"
          echo "Debug mode: ${{ github.event.inputs.debug }}"
